apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-js-container
        image: kadiransari7208/node-js-db-app:02
      - name: node-js-mongo-container
        image: mongo          
        env:
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: mongo-config 
                key: MONGO_HOST
          - name: MONGO_PORT
            valueFrom:  
              configMapKeyRef:
                name: mongo-config
                key: MONGO_PORT
      
